/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mcreator.hyderemods;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class HyderemodsModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();

	public HyderemodsModElements() {
		sounds.put(new ResourceLocation("hyderemods", "test"), new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "test")));
		sounds.put(new ResourceLocation("hyderemods", "voixsoldat1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "voixsoldat1")));
		sounds.put(new ResourceLocation("hyderemods", "voixmarchant1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "voixmarchant1")));
		sounds.put(new ResourceLocation("hyderemods", "voix_de_gleshni"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "voix_de_gleshni")));
		sounds.put(new ResourceLocation("hyderemods", "choque_electrique"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "choque_electrique")));
		sounds.put(new ResourceLocation("hyderemods", "soufle_du_vend"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "soufle_du_vend")));
		sounds.put(new ResourceLocation("hyderemods", "voix_garde_du_village1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "voix_garde_du_village1")));
		sounds.put(new ResourceLocation("hyderemods", "que_veut_tu_me_vendre_acheteur"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "que_veut_tu_me_vendre_acheteur")));
		sounds.put(new ResourceLocation("hyderemods", "quest_vendeur_q1_village1"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "quest_vendeur_q1_village1")));
		sounds.put(new ResourceLocation("hyderemods", "sanglier"), new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "sanglier")));
		sounds.put(new ResourceLocation("hyderemods", "ataque_enemis"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "ataque_enemis")));
		sounds.put(new ResourceLocation("hyderemods", "competence_activation"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("hyderemods", "competence_activation")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("hyderemods").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == HyderemodsModElements.ModElement.class)
						elements.add((HyderemodsModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(HyderemodsModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}

	private int messageID = 0;

	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		HyderemodsMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}

	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}

		protected final HyderemodsModElements elements;
		protected final int sortid;

		public ModElement(HyderemodsModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
